modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "MIT"
clientSideOnly = true

[[mods]]
modId = "tradeenchantmentdisplay"
version = "${version}"
displayName = "Trade Enchantment Display"
authors = "iMoonDay"
description = "Automatically display the enchantment name of traded items"
logoFile = "icon.png"

[[dependencies.tradeenchantmentdisplay]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tradeenchantmentdisplay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

