modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/iMoonDay/TradeEnchantmentDisplay/issues"
license = "MIT"
clientSideOnly = true

[[mods]]
modId = "tradeenchantmentdisplay"
version = "${version}"
displayName = "Trade Enchantment Display"
authors = "iMoonDay"
description = "Automatically display the enchantment name of traded items"
logoFile = "icon.png"
displayURL = "https://modrinth.com/project/trade-enchantment-display"

[[dependencies.tradeenchantmentdisplay]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tradeenchantmentdisplay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tradeenchantmentdisplay]]
modId = "cloth-config"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

